import "./globals.css";

import { Chewy, Andika, Oxygen } from "next/font/google";
import Layout from "@/components/header/Layout";
import NextNProgress from "nextjs-progressbar";
import ProgressBar from "@/components/header/ProgressBar";

const chewy = Chewy({
  subsets: ["latin"],
  variable: "--font-chewy",
  weight: "400",
});

const andika = Andika({
  subsets: ["latin"],
  variable: "--font-andika",
  weight: "400",
});

const oxygen = Oxygen({
  subsets: ["latin"],
  variable: "--font-oxygen",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div
        className={`${chewy.variable} ${andika.variable} ${oxygen.variable} `}
      >
        <Layout children={children} />
      </div>
    </html>
  );
}
